# Strands Analyst Configuration

# RSS feed and news agent configuration (merged)
rss:
  # Default number of items to fetch and display
  default_items: 10
  
  # Maximum number of items allowed in a single request
  max_items: 50
  
  # Default timeout for RSS feed requests (seconds)
  timeout: 30
  
  # Whether to include full content in RSS items (vs just summaries)
  include_full_content: true

# Article download configuration
article:
  # Default output directory for downloaded articles
  output_dir: "refer/articles"
  
  # Default timeout for article requests (seconds)
  timeout: 30
  
  # Whether to download images by default
  download_images: true
  
  # Maximum number of images to download per article
  max_images: 20

# Markdown conversion configuration
markdown:
  # Output format for markdown files
  output_format: "markdown"
  
  # Heading style (ATX or SETEXT)
  heading_style: "ATX"
  
  # Whether to include frontmatter metadata by default
  include_metadata: true

# Site metadata analysis configuration
sitemeta:
  # Default output directory for site metadata reports
  output_dir: "refer/sitemeta"
  
  # Whether to save response as markdown file by default
  save_markdown: true
  
  # Timeout for metadata requests (seconds)
  timeout: 30

# News analysis configuration
news:
  # Default output directory for news analysis reports
  output_dir: "refer/news"
  
  # Whether to save response as markdown file by default
  save_markdown: true
  
  # Timeout for news requests (seconds)
  timeout: 30

# Chat interface configuration
chat:
  # Default session directory for chat conversations
  session_dir: "refer/chat-sessions"
  
  # Default conversation window size for context management
  window_size: 20
  
  # Whether to save conversation summaries on exit by default
  save_on_exit: true
  
  # Session timeout in minutes (0 = no timeout)
  session_timeout: 0

# General application settings
app:
  # Application name
  name: "Strands Analyst"
  
  # Version
  version: "0.1.0"

# Logging configuration
logging:
  # Default logging level (DEBUG, INFO, WARNING, ERROR)
  level: "INFO"
  
  # Whether to show logs in non-verbose mode
  show_by_default: false
  
  # Whether to show logs when verbose flag is used
  show_in_verbose: true
  
  # Log format string
  format: "%(levelname)s | %(name)s | %(message)s"
  
  # Whether logging is completely disabled
  enabled: true

# Metrics reporting configuration  
metrics:
  # Whether to show metrics by default (without verbose flag)
  show_by_default: false
  
  # Whether to show metrics when verbose flag is used
  show_in_verbose: true
  
  # Which metrics to include in reports
  include:
    model: true
    tokens: true
    duration: true
    latency: true
    tool_usage: true
    cycles: false  # Only show for verbose or multi-cycle runs
  
  # Display formatting options
  display:
    # Whether to use colors in output
    colors: true
    
    # Minimalist mode (less detailed output)
    minimalist: true
    
    # Add spacing around metrics
    add_spacing: true

# Amazon Bedrock Model Configuration
# Optimizes agent performance using AWS Bedrock model provider
bedrock:
  # Default model configuration
  model:
    # Primary model ID for general analysis tasks
    # Using Claude 3.7 Sonnet inference profile for optimal performance and availability
    default_model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
    
    # Model IDs for specific use cases (overrides default when specified)
    models:
      # Fast model for quick analysis and simple tasks
      fast: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      
      # Reasoning model for complex analysis tasks
      reasoning: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      
      # Chat model for conversational interactions
      chat: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
  
  # Performance optimization parameters
  performance:
    # Temperature: Controls response randomness (0.0-1.0)
    # Lower = more focused/consistent, Higher = more creative/varied
    temperature:
      default: 0.3        # Balanced for analysis tasks
      sitemeta: 0.2       # More focused for metadata extraction
      news: 0.4           # Slightly more varied for news summaries
      article: 0.3        # Balanced for article analysis
      chat: 0.5           # More conversational for chat
    
    # Top-p: Nucleus sampling for response diversity (0.0-1.0)
    # Lower = more focused vocabulary, Higher = more diverse
    top_p:
      default: 0.8
      sitemeta: 0.7       # More focused for structured data
      news: 0.8           # Balanced for varied content
      article: 0.8        # Balanced for article analysis
      chat: 0.9           # More diverse for conversation
    
    # Maximum tokens to generate
    max_tokens:
      default: 4096
      sitemeta: 2048      # Shorter for metadata analysis
      news: 3072          # Medium for news summaries
      article: 8192       # Longer for detailed article analysis
      chat: 4096          # Balanced for conversation
    
    # Stop sequences to control generation
    stop_sequences:
      default: []
      # Custom stop sequences can be added per use case
  
  # Advanced optimization settings
  advanced:
    # Enable streaming mode for faster perceived response time
    streaming: true
    
    # AWS region for Bedrock service (choose closest for better latency)
    region_name: "us-east-1"
    
    # Content safety and guardrails
    guardrails:
      # Guardrail ID for content filtering (optional)
      guardrail_id: null
      
      # Enable content filtering
      enable_content_filtering: false
    
    # Caching optimizations for better performance
    caching:
      # Cache system prompts for reuse across requests
      cache_prompt: true
      
      # Cache tool definitions for reuse
      cache_tools: true
      
      # Cache timeout in seconds (0 = no timeout)
      cache_timeout: 3600
    
    # Request timeout settings
    timeouts:
      # Connection timeout in seconds
      connection_timeout: 30
      
      # Read timeout in seconds
      read_timeout: 120
      
      # Total request timeout in seconds
      total_timeout: 180
  
  # Agent-specific optimizations
  agents:
    # Site metadata agent optimizations
    sitemeta:
      # Override global model for this specific agent
      model_id: null  # Uses default if null
      
      # Enable reasoning mode for complex site analysis
      reasoning_mode: false
      
      # Custom system prompt optimizations
      optimize_system_prompt: true
    
    # News agent optimizations
    news:
      model_id: null
      reasoning_mode: false
      optimize_system_prompt: true
      
      # Batch processing for multiple RSS items
      batch_processing: true
    
    # Article agent optimizations
    article:
      model_id: null
      reasoning_mode: true  # Enable for detailed article analysis
      optimize_system_prompt: true
    
    # Chat agent optimizations
    chat:
      model_id: null
      reasoning_mode: false
      optimize_system_prompt: true
      
      # Session-specific optimizations
      session_optimization: true
      
      # Enable multimodal support for chat
      multimodal: true
  
  # Usage and cost optimization
  cost_optimization:
    # Enable cost tracking and reporting
    track_usage: true
    
    # Warn when approaching cost thresholds
    cost_warnings: true
    
    # Maximum tokens per hour (0 = no limit)
    hourly_token_limit: 0
    
    # Maximum cost per hour in USD (0.0 = no limit)
    hourly_cost_limit: 0.0

# Community Tools Configuration
# Controls which Strands community tools are available to agents
community_tools:
  # Global tool settings
  enabled: true
  
  # Tool consent and safety settings
  consent:
    # Require user confirmation for potentially sensitive operations
    require_consent: true
    
    # Bypass consent for non-destructive tools (read-only operations)
    bypass_for_safe_tools: true
    
    # Tools that always require consent regardless of bypass setting
    always_require_consent:
      - "shell"
      - "python_repl" 
      - "file_write"
      - "editor"
      - "use_agent"
      - "swarm"
      - "workflow"
  
  # Human-in-the-loop configuration
  human_in_loop:
    # Enable handoff to user functionality
    enabled: true
    
    # Default timeout for user responses (seconds, 0 = no timeout)
    response_timeout: 300
    
    # Break out of agent loop on handoff by default
    default_breakout: false
  
  # Tool categories and enablement
  # Set to false to disable entire categories
  categories:
    web_network: true
    file_operations: true
    code_system: true
    automation_workflow: true
    memory_storage: true
    communication: true
    utilities: true
    aws_services: false  # Disabled by default for security
  
  # Individual tool configuration
  # Tools are organized by category for easy management
  tools:
    # Web & Network tools
    web_network:
      http_request:
        enabled: true
        require_consent: false
        description: "Make HTTP requests to external APIs and websites"
      
      rss:
        enabled: true
        require_consent: false  
        description: "Fetch and parse RSS feeds"
      
      tavily:
        enabled: false  # Requires API key
        require_consent: false
        description: "Web search using Tavily API"
    
    # File Operations tools
    file_operations:
      file_read:
        enabled: true
        require_consent: false
        description: "Read files from the local filesystem"
      
      file_write:
        enabled: true
        require_consent: true
        description: "Write and modify files on the local filesystem"
      
      editor:
        enabled: true
        require_consent: true
        description: "Interactive text editor for file modifications"
    
    # Code & System tools
    code_system:
      python_repl:
        enabled: true
        require_consent: true
        description: "Execute Python code with persistent state"
      
      shell:
        enabled: true
        require_consent: true
        description: "Execute shell commands with PTY support"
      
      calculator:
        enabled: true
        require_consent: false
        description: "Perform mathematical calculations"
      
      environment:
        enabled: true
        require_consent: false
        description: "Access environment variables and system information"
    
    # Automation & Workflow tools
    automation_workflow:
      use_agent:
        enabled: true
        require_consent: true
        description: "Start new AI agents with different prompts and models"
      
      swarm:
        enabled: false  # Advanced feature, disabled by default
        require_consent: true
        description: "Create and coordinate teams of AI agents"
      
      workflow:
        enabled: false  # Advanced feature, disabled by default  
        require_consent: true
        description: "Advanced workflow orchestration"
      
      cron:
        enabled: false  # Scheduling, disabled by default
        require_consent: true
        description: "Schedule tasks and workflows"
      
      batch:
        enabled: true
        require_consent: false
        description: "Process multiple items in batches"
    
    # Memory & Storage tools
    memory_storage:
      memory:
        enabled: true
        require_consent: false
        description: "Store and retrieve information across conversations"
      
      journal:
        enabled: true
        require_consent: false
        description: "Maintain a journal of activities and insights"
    
    # Communication tools
    communication:
      handoff_to_user:
        enabled: true
        require_consent: false
        description: "Pause execution and request user input"
      
      slack:
        enabled: false  # Requires configuration
        require_consent: true
        description: "Send messages and interact with Slack"
    
    # Utility tools
    utilities:
      current_time:
        enabled: true
        require_consent: false
        description: "Get current date and time"
      
      sleep:
        enabled: true
        require_consent: false
        description: "Pause execution for specified duration"
      
      stop:
        enabled: true
        require_consent: false
        description: "Stop agent execution gracefully"
      
      think:
        enabled: true
        require_consent: false
        description: "Recursive thinking for sophisticated analysis"
      
      use_llm:
        enabled: true
        require_consent: false
        description: "Use different language models for specialized tasks"
    
    # AWS Services (disabled by default for security)
    aws_services:
      use_aws:
        enabled: false
        require_consent: true
        description: "Interact with AWS services"
  
  # Agent-specific tool configurations
  # Override global settings for specific agents
  agent_overrides:
    chat:
      # Enable more tools for interactive chat
      enabled_categories: ["web_network", "file_operations", "code_system", "utilities", "communication", "memory_storage"]
      
      # Chat-specific tool settings
      tools:
        python_repl:
          require_consent: false  # Less friction in chat mode
        file_read:
          require_consent: false
        calculator:
          require_consent: false
        
    sitemeta:
      # Limited tools for site metadata analysis
      enabled_categories: ["web_network", "utilities"]
      
    news:
      # News-specific tools
      enabled_categories: ["web_network", "utilities", "memory_storage"]
      
    article:
      # Article analysis tools
      enabled_categories: ["web_network", "file_operations", "utilities", "memory_storage"]
      
    htmlmd:
      # HTML to markdown conversion tools
      enabled_categories: ["file_operations", "utilities"]