# Strands Analyst Configuration

# RSS feed and news agent configuration (merged)
rss:
  # Default number of items to fetch and display
  default_items: 10
  
  # Maximum number of items allowed in a single request
  max_items: 50
  
  # Default timeout for RSS feed requests (seconds)
  timeout: 30
  
  # Whether to include full content in RSS items (vs just summaries)
  include_full_content: true

# Article download configuration
article:
  # Default output directory for downloaded articles
  output_dir: "refer/articles"
  
  # Default timeout for article requests (seconds)
  timeout: 30
  
  # Whether to download images by default
  download_images: true
  
  # Maximum number of images to download per article
  max_images: 20

# Markdown conversion configuration
markdown:
  # Output format for markdown files
  output_format: "markdown"
  
  # Heading style (ATX or SETEXT)
  heading_style: "ATX"
  
  # Whether to include frontmatter metadata by default
  include_metadata: true

# General application settings
app:
  # Application name
  name: "Strands Analyst"
  
  # Version
  version: "0.1.0"

# Logging configuration
logging:
  # Default logging level (DEBUG, INFO, WARNING, ERROR)
  level: "INFO"
  
  # Whether to show logs in non-verbose mode
  show_by_default: false
  
  # Whether to show logs when verbose flag is used
  show_in_verbose: true
  
  # Log format string
  format: "%(levelname)s | %(name)s | %(message)s"
  
  # Whether logging is completely disabled
  enabled: true

# Metrics reporting configuration  
metrics:
  # Whether to show metrics by default (without verbose flag)
  show_by_default: false
  
  # Whether to show metrics when verbose flag is used
  show_in_verbose: true
  
  # Which metrics to include in reports
  include:
    model: true
    tokens: true
    duration: true
    latency: true
    tool_usage: true
    cycles: false  # Only show for verbose or multi-cycle runs
  
  # Display formatting options
  display:
    # Whether to use colors in output
    colors: true
    
    # Minimalist mode (less detailed output)
    minimalist: true
    
    # Add spacing around metrics
    add_spacing: true